INSERT INTO modules VALUES ('EL4880D', 'Experimental Syntax', '5');
INSERT INTO modules VALUES ('MD5140', 'Medicine', '1');
INSERT INTO modules VALUES ('HY3201', 'Indonesia: History, Economy and Society', '4');
INSERT INTO modules VALUES ('NM4852', 'Department Exchange Module', '5');
INSERT INTO modules VALUES ('BMT5101', 'Applied Data Science & Vizualization', '4');
INSERT INTO modules VALUES ('MA6223', 'Topics in Logic II', '4');
INSERT INTO modules VALUES ('UTC2400', 'Community Leadership', '4');
INSERT INTO modules VALUES ('YSS4104', 'Economics Capstone Project', '10');
INSERT INTO modules VALUES ('CS5421', 'Database Applications Design and Tuning', '4');
INSERT INTO modules VALUES ('LSM4211', 'Toxicology', '4');
INSERT INTO modules VALUES ('MKT3417', 'Customer Relationship Management', '4');
INSERT INTO modules VALUES ('TRA3204', 'Literary Translation', '4');
INSERT INTO modules VALUES ('EE5110', 'Special Topics in Automation and Control', '4');
INSERT INTO modules VALUES ('YHU3369', 'Philosophy of Race', '5');
INSERT INTO modules VALUES ('GEH1011', 'Film and History', '4');
INSERT INTO modules VALUES ('PF4309', 'Infrastructure Operations and Maintenance', '4');
INSERT INTO modules VALUES ('MUA3190', 'Applied Voice Major Study 3B', '4');
INSERT INTO modules VALUES ('GEH1066', 'Art Movements and -isms', '4');
INSERT INTO modules VALUES ('LL5431', 'Choice of Law: Practice and Theories', '4');
INSERT INTO modules VALUES ('LL4245V', 'Regulatory Foundations of Public Law', '5');
INSERT INTO modules VALUES ('MA3211', 'Complex Analysis I', '4');
INSERT INTO modules VALUES ('RVSS1000', 'Exploring Sense of Place', '4');
INSERT INTO modules VALUES ('PC3238', 'Fluid Dynamics', '4');
INSERT INTO modules VALUES ('CS3220', 'Computer Architecture', '4');
INSERT INTO modules VALUES ('MS3550', 'Malay Studies Internship', '4');
INSERT INTO modules VALUES ('ME4212', 'Aircraft Structures', '4');
INSERT INTO modules VALUES ('CH3551', 'FASS Undergraduate Research Opportunity (UROP)', '4');
INSERT INTO modules VALUES ('BPM1705', 'Understanding How Business Works', '0');
INSERT INTO modules VALUES ('GEM1919', 'Thinking in Systems: Diseases and Healthcare', '4');
INSERT INTO modules VALUES ('FIN3713', 'Bank Management', '4');
INSERT INTO modules VALUES ('LL4194', 'Partnership and LLP Law', '4');
INSERT INTO modules VALUES ('LL5210', 'Intellectual Property And International Trade', '4');
INSERT INTO modules VALUES ('OT5402B', 'Seismic Processing and Imaging', '2');
INSERT INTO modules VALUES ('YHU4234', 'Trauma, Loss, Exile and the Literary Imagination', '5');
INSERT INTO modules VALUES ('LL4017', 'Contract and Commercial Law in Civil-Law Asia', '4');
INSERT INTO modules VALUES ('MNO4313E', 'SIMHC: Managerial and Organisational Cognition', '4');
INSERT INTO modules VALUES ('LL5348V', 'Monetary Law in Comparative Perspective', '5');
INSERT INTO modules VALUES ('CS5477', '3D Computer Vision', '4');
INSERT INTO modules VALUES ('LLJ5398', 'University Research Opportunities Programme', '4');
INSERT INTO modules VALUES ('HY3262', 'Buddhism In Southeast Asian History', '4');
INSERT INTO modules VALUES ('CH6263', 'Translation: Formal, Cultural, Political', '4');
INSERT INTO modules VALUES ('HY2251', 'From the Wheel to the Web', '4');
INSERT INTO modules VALUES ('BSP1707A', 'Managerial Economics: Exposure', '2');
INSERT INTO modules VALUES ('BMA5135', 'Execution of Digital Strategy in the real world', '4');
INSERT INTO modules VALUES ('LLJ5131V', 'Law, Governance & Development in Asia', '5');
INSERT INTO modules VALUES ('GE4660', 'Independent Study', '5');
INSERT INTO modules VALUES ('NM2209', 'Social Psychology of New Media', '4');
INSERT INTO modules VALUES ('TCE4247', 'Treatment Plant Hydraulics', '4');
INSERT INTO modules VALUES ('LL5111V', 'International Copyright Law and Policy', '5');
INSERT INTO modules VALUES ('NUR6007', 'Research Leadership and Professional Development', '4');
INSERT INTO modules VALUES ('LL6049', 'Principles Of Conflict Of Laws', '4');
INSERT INTO modules VALUES ('LLJ5300', 'Copyright in the Internet Age', '4');
INSERT INTO modules VALUES ('EE3505C', 'Electrical Energy Systems', '4');
INSERT INTO modules VALUES ('LLJ5150', 'International Investment Law and Arbitration', '4');
INSERT INTO modules VALUES ('UWC2101D', 'Writing and Critical Thinking: Narrative in Everyday Life', '4');
INSERT INTO modules VALUES ('GEK2049', 'Pirates, Oceans and the Maritime World', '4');
INSERT INTO modules VALUES ('DSA4212', 'Optimisation for Large-Scale Data-Driven Inference', '4');
INSERT INTO modules VALUES ('GMS6284D', 'Plastic, Reconstructive & Aesthetic Surg', '4');
INSERT INTO modules VALUES ('ES1000', 'Foundation Academic English', '0');
INSERT INTO modules VALUES ('AR4421', 'Architecture Internship Programme', '8');
INSERT INTO modules VALUES ('YSS2244', 'Markets, Morality and Politics', '5');
INSERT INTO modules VALUES ('LLJ5334', 'Law and Society in Southeast Asia', '4');
INSERT INTO modules VALUES ('PP5232', 'Applied Environmental Economics', '4');
INSERT INTO modules VALUES ('PS4239', 'Seminar in International Relations of Southeast Asia', '5');
INSERT INTO modules VALUES ('TCE2407', 'Engineering & Uncertainty Analyses', '4');
INSERT INTO modules VALUES ('EU4217', 'Comparative Business Cultures', '5');
INSERT INTO modules VALUES ('SC2211', 'Medical Sociology', '4');
INSERT INTO modules VALUES ('LL4251V', 'International Humanitarian Law', '5');
INSERT INTO modules VALUES ('SPH6201D', 'Independent Study (Health Policy and Systems)', '4');
INSERT INTO modules VALUES ('GMS5313', 'Serious games: Applications in healthcare', '1');
INSERT INTO modules VALUES ('LL5331', 'The Rule of Law', '4');
INSERT INTO modules VALUES ('FSC5205', 'Forensic Science in Major Cases', '4');
INSERT INTO modules VALUES ('BN4501', 'Engineering Biology', '4');
INSERT INTO modules VALUES ('CH5222R', 'Topics in Modern Chinese Literature', '5');
INSERT INTO modules VALUES ('CHC5313', 'Thematics in Chinese Literature', '4');
INSERT INTO modules VALUES ('CS5342', 'Multimedia Computing and Applications', '4');
INSERT INTO modules VALUES ('LC1002C', 'Introduction to Legal Theory (C)', '4');
INSERT INTO modules VALUES ('CE5886', 'Topics in Concrete Engineering: Specialized', '4');
INSERT INTO modules VALUES ('IND5021', 'Managing the Digital Supply Chain', '4');
INSERT INTO modules VALUES ('EM1202', 'English for Academic Purposes (Music) 2', '0');
INSERT INTO modules VALUES ('CP5104', 'Graduate Project in Computing', '4');
INSERT INTO modules VALUES ('SC2209', 'Money, Business and Social Networks', '4');
INSERT INTO modules VALUES ('GEC1000', 'Globalisation and New Media', '4');
INSERT INTO modules VALUES ('LL5400', 'Biomedical Law & Ethics', '8');
INSERT INTO modules VALUES ('PR5304', 'Fundamental Topics in Pharmaceutical Science', '4');
INSERT INTO modules VALUES ('MA5213', 'Advanced Partial Differential Equations', '4');
INSERT INTO modules VALUES ('LL5457V', 'International Human Rights Law', '5');
INSERT INTO modules VALUES ('UTC3101', 'Independent Study', '4');
INSERT INTO modules VALUES ('BMK5206E', 'Special Topics in Marketing Analytics and Insights', '4');
INSERT INTO modules VALUES ('MKT4415G', 'SIM: Customer Analytics and Visualization', '4');
INSERT INTO modules VALUES ('AR2228', 'History & Theory of Architecture II', '4');
INSERT INTO modules VALUES ('LLJ5297', 'Practice of Corporate Finance and the Law', '4');
INSERT INTO modules VALUES ('LL5208V', 'Advanced Criminal Legal Process', '5');
INSERT INTO modules VALUES ('HY3236', 'The Struggle for India, 1920-1964', '4');
INSERT INTO modules VALUES ('GEH1069', 'Art in Asia: Through Media, Style, Space and Time', '4');
INSERT INTO modules VALUES ('MA5238', 'Fourier Analysis', '4');
INSERT INTO modules VALUES ('YSC3228', 'Inorganic Chemistry with Laboratory', '5');
INSERT INTO modules VALUES ('GMS6242C', 'OB Anaesthesia Clinical & Research Prog', '3');
INSERT INTO modules VALUES ('CS6217', 'Topics in Prog. Languages & Software Engineering', '4');
INSERT INTO modules VALUES ('SW5881A', 'Evidence Based Behavioural Strategies for Social Work Practice', '4');
INSERT INTO modules VALUES ('SPH5206', 'Urban Field Epidemiology', '4');
INSERT INTO modules VALUES ('TS3880', 'Topics in Group Practice Research', '8');
INSERT INTO modules VALUES ('USP2201', 'Food Production and Society in Southeast Asia', '2');
INSERT INTO modules VALUES ('MA5244', 'Advanced Topics in Operations Research', '4');
INSERT INTO modules VALUES ('GEH1053', 'Film Art and Human Concerns', '4');
INSERT INTO modules VALUES ('NM3215', 'Advertising Strategies', '4');
INSERT INTO modules VALUES ('MLE2103', 'Phase Transformation and Kinetics', '3');
INSERT INTO modules VALUES ('LLJ5358Z', 'ICC Arbitration', '2.5');
INSERT INTO modules VALUES ('EN3224', 'The Twentieth Century', '4');
INSERT INTO modules VALUES ('MUA3242', 'Collaborative Piano - Instrumental Accompaniment', '2');
INSERT INTO modules VALUES ('ME5105', 'Shock and Vibration Control', '4');
INSERT INTO modules VALUES ('EE4001', 'B.Eng. Dissertation', '12');
INSERT INTO modules VALUES ('LL5193', 'An Introduction to Negotiating & Drafting Commercial Contracts', '4');
INSERT INTO modules VALUES ('LL6442', 'Digital Trade and Digital Economy', '4');
INSERT INTO modules VALUES ('MA1507', 'Advanced Calculus', '4');
INSERT INTO modules VALUES ('PP5231', 'Ethics and Global Governance', '4');
INSERT INTO modules VALUES ('EN3219', 'Twenty-First Century British Fiction', '4');
INSERT INTO modules VALUES ('UQR2212', 'How Linguists Work', '4');
INSERT INTO modules VALUES ('ESP4901A', 'Research Project', '12');
INSERT INTO modules VALUES ('YHU3211', 'Chinese Tales of the Strange', '5');
INSERT INTO modules VALUES ('PS4314', 'Data Analytics in Political Science', '5');
INSERT INTO modules VALUES ('LLJ5071V', 'International Patent Law, Policy and Practice', '5');
INSERT INTO modules VALUES ('CE5106A', 'Ground Improvement for Soft Soils', '2');
INSERT INTO modules VALUES ('TR4049T', 'Seminars in Entrepreneurship - Lean Startup: Market Validation', '4');
INSERT INTO modules VALUES ('HY3237', 'Issues in Thai History', '4');
INSERT INTO modules VALUES ('TS2242', 'Intercultural Performance Practice', '4');
INSERT INTO modules VALUES ('EE5061', 'Industrial Control and Programming', '2');
INSERT INTO modules VALUES ('LLD5034', 'International Regulation of Shipping', '4');
INSERT INTO modules VALUES ('GE5226', 'GIS Applications', '4');
INSERT INTO modules VALUES ('YHU3361', 'Writing Hybrid', '5');
INSERT INTO modules VALUES ('MUA4110', 'Chamber Music in Mixed Ensemble', '2');
INSERT INTO modules VALUES ('LL6296', 'Imitation, Innovation and Intellectual Property', '4');
INSERT INTO modules VALUES ('GMS6228', 'Radiology Program', '1');
INSERT INTO modules VALUES ('PS3238', 'International Political Economy', '4');
INSERT INTO modules VALUES ('YSS3292', 'Palestinian Politics in Changing Middle East', '5');
INSERT INTO modules VALUES ('LL5457', 'International Human Rights Law', '4');
INSERT INTO modules VALUES ('ME6102', 'Topics in Applied Mechanics: Mechanics of Materials', '4');
INSERT INTO modules VALUES ('LSM4261', 'Marine Biology', '4');
INSERT INTO modules VALUES ('YHU2318', 'State and Society in the Ancient Near East', '5');
INSERT INTO modules VALUES ('HLE5102', 'Clinical Decision-Making: Ethical and Legal Aspects', '2');
INSERT INTO modules VALUES ('TCE5604', 'Advanced Concrete Technology', '4');
INSERT INTO modules VALUES ('UTOA2002PL', 'Undergraduate Teaching Opportunities Programme (UTOP)', '4');
INSERT INTO modules VALUES ('PL3254', 'Trauma Psychology', '4');
INSERT INTO modules VALUES ('YIR3301G', 'Independent Reading and Research', '2.5');
INSERT INTO modules VALUES ('PM5112', 'Research Methods', '4');
INSERT INTO modules VALUES ('YHU3293', 'Japanese Woodblock Prints', '5');
INSERT INTO modules VALUES ('ACC2706', 'Managerial Accounting', '4');
INSERT INTO modules VALUES ('ME2115', 'Mechanics Of Machines', '4');
INSERT INTO modules VALUES ('LL5125V', 'Law And Development In China', '5');
INSERT INTO modules VALUES ('MA5402', 'Graduate Internship in Mathematics II', '8');
INSERT INTO modules VALUES ('YSS3229', 'Urbanization and the Environment', '5');
INSERT INTO modules VALUES ('GET1049', 'Thinking Strategically', '4');
INSERT INTO modules VALUES ('CN3135E', 'Process Safety, Health and Environment', '3');
INSERT INTO modules VALUES ('IE5999', 'Graduate Seminars', '4');
INSERT INTO modules VALUES ('CN4238E', 'Chemical & Biochemical Process Modeling', '4');
